apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app-svc
  labels:
    app: gitops-demo-app
spec:
  selector:
    app: gitops-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32459
  type: NodePort
